apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: -.monolithic-applications
build:
  artifacts:
  - image: monolothicapp
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/monolithicapp.yaml
